In [4]:
# Problem 1 - Steepest Descent and Conjugate Gradient
import numpy as np

A = np.array([[10.,1.,2.,3.,4.], [1.,9.,-1.,2.,-3.], [2.,-1.,7.,3.,-5.], [3.,2.,3.,12.,-1.], [4.,-3.,-5.,-1.,15.]])
# b = np.array([[12],[-27],[14],[-17],[12]])
b = np.array([12.,-27.,14.,-17.,12.])
n = len(A)
x0 = np.zeros(n)
k = 0
M = 100
delta = 10**(-8) #tolerance

def SD(x0,A,b,n,k,M,delta):
    for k in range(M):
        v = b - np.dot(x0,A)
        print(v)
        t = np.dot(v,v)/np.dot(v,np.dot(v,A))
        x1 = x0 + t*v
        if np.sqrt(np.dot((x1-x0),(x1-x0)))<delta:
            return x1, k
        else:
            k = k+1
            x0 = x1.copy()
    return x1,k

def CG(x0,A,b,M,eps,delta):
    r0 = b-A*x0
    v0 = r0
    while k<M:
        if np.sqrt(np.inner(v,v))<delta:
            stop
        t = np.inner(r,r)/np.inner(v,np.dot(A,v))
        x = x0 + t*v
        r = r0.copy()
        
SD = SD(A,b,n,x0,k,M,delta)
print(SD)

[-113.  320.  -33.  197. -251.]


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [3]:
# Problem 2 - Power Method
import numpy as np

A = np.array([[5,4,1,1], [4,5,1,1], [1,1,4,2], [1,1,2,4]])
A1 = np.linalg.inv(A)
n = len(A)
x = np.random.rand(A.shape[0])
M = 100

def Phi(x):
    phix = x.item(1)
    return phix

def PowerMethod(A, x, M): #normalized
    for _ in range(M):
        y = np.dot(A, x)
        r = Phi(y)/Phi(x)
        y_norm = np.linalg.norm(y)
        x = y/y_norm
    return x,r

def PowerUnNorm(A, x, M): #un-normalized
    for _ in range(M):
        y = np.dot(A, x)
        r = Phi(y)/Phi(x)
        x = y
    return x,r

PMN = PowerMethod(A,x,M)
PMI = PowerMethod(A1,x,M) #inverse PM

print PMN
print PMI

PUN = PowerUnNorm(A,x,M)
print PUN

# Notes - the un-normalized Power Method is giving nowhere near true results.

(array([ 0.63245553,  0.63245553,  0.31622777,  0.31622777]), 10.0)
(array([ -7.07106781e-01,   7.07106781e-01,   8.67361738e-18,
         5.20417043e-18]), 1.0000000000000002)
(array([  4.74469254e+99,   4.74469254e+99,   2.37234627e+99,
         2.37234627e+99]), 10.0)


In [14]:
# Problem 3 - Gram-Schmidt, traditional and modified
import numpy as np

test = np.random.rand(20,10)
test2 = np.fromfunction(lambda i, j: ((2*i-21)/19)**(j-1), (20, 10))
n = len(test)
m = len(np.transpose(test))
    
def GramSchmidt(m,n,A):
    C = np.zeros((n,m))
    Q = np.zeros((n,m))
    R = np.zeros((n,m))
    for j in xrange(m):
        for i in xrange(j):
            R[i,j] = np.dot(A[:,j],Q[:,i])
        C[:,j] = A[:,j]
        for i in xrange(j):
            C[:,j]=C[:,j]-R[i,j]*Q[:,i]
        R[j,j] = np.linalg.norm(C[:,j])
        Q[:,j] = C[:,j]/R[j,j]
    return R, Q

def GramSchmidtMod(m,n,A):
    for k in xrange(m):
        A[:,k] = A[:,k]/np.linalg.norm(A[:,k])
        for j in range(k+1,m):
            A[:,j] = A[:,j] - np.dot(A[:,j],A[:,k])*A[:,k]
    return A

A = GramSchmidt(m,n,test)
A2 = GramSchmidt(m,n,test2)
B = GramSchmidtMod(m,n,test)
B2 = GramSchmidtMod(m,n,test2)

print A
print A2
print B
print B2

#note - ran out of time to add testing criterion

 (array([[ 2.45775472,  1.89788688,  1.4908659 ,  1.86186064,  2.24717837,
         1.92833757,  2.1433231 ,  1.36634518,  1.35542666,  1.9059001 ],
       [ 0.        ,  1.96100248,  0.59068774,  0.69886087,  0.45277772,
         1.18336479,  0.52772771,  0.49709024,  1.21843905,  0.68018611],
       [ 0.        ,  0.        ,  1.31768844,  0.37449446,  0.10072456,
         0.23758088,  0.01120921,  0.19745884, -0.12813982,  0.30787312],
       [ 0.        ,  0.        ,  0.        ,  1.28558051,  0.57430589,
         0.14285535, -0.32224894,  0.42778672,  0.01262333,  0.83354113],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  1.48806314,
         0.22228053,  0.87237802,  0.15505659,  0.09058103,  0.14677074],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         1.16506489,  0.6347122 ,  0.39555442, -0.10436845,  0.23479234],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  1.09774842,  0.277462