<font color='red'>
## Comments:
<font color='red'>

<font color='red'>
## Your Gauss-Seidel algorithm is actually not right. You are using the x1 vector, which comes from the solution of the Jacobi iteration (already the true solution of the system). In your code, you copied the true solution from x1 to x, and that's why you achieved convergence in 2 steps. Normally it needs around 10 steps to get convergence for this problem: 
<font color='red'>

<font color='red'>
## Grade: A-
<font color='red'>

In [5]:
# Jacobi  and  Gauss-Seidel  methods
import numpy as np

A = np.array([[4, -1, 1], [4, -8, 1], [-2, 1, 5]])
b = np.array([[7],[-21],[15]])
n = len(A)
x = np.zeros(n)
x1 = np.zeros(n)
u = np.zeros(n)
delta = 10**(-7) #tolerance
k = 0
M = 100

def Jacobi(n,A,b,x,u,delta,k,M):
    while k<M:
        for i in xrange(n):
            tmp_sum = np.dot(A[i,:n], x[:n]) - (A[i,i]*x[i])
            u[i] = (b[i] - tmp_sum)/A[i,i]
        for i in xrange(n):
            x1[i] = u[i]
        if np.sqrt(np.inner((x1-x),(x1-x)))<delta:
            return x1, k
        else:
            k = k+1
            x = x1.copy()
    return x1, k

def GSI(n,A,b,x,delta,k,M):
    while k<M:
        for i in xrange(n):
            tmp_sum = np.dot(A[i,:n], x[:n]) - (A[i,i]*x[i])
            x[i] = (b[i] - tmp_sum)/A[i,i]
        if np.sqrt(np.inner((x1-x),(x1-x)))<delta:
            return x1, k
        else:
            k = k+1
            x = x1.copy()
            k = k+1
    return x, k

J = Jacobi(n,A,b,x,u,delta,k,M)
GS = GSI(n,A,b,x,delta,k,M)
print J, GS

(array([ 1.99999997,  3.99999999,  3.00000001]), 16) (array([ 1.99999997,  3.99999999,  3.00000001]), 2)


In [8]:
# Problem 2 - Successive Over-Relaxation & Symmetric Successive Over-Relaxation
import numpy as np

A = np.array([[3., -1., 1.], [-1., 3., -1.], [1., -1., 3.]])
b = np.array([-1.,7.,-7.])
n = len(A)
z = np.zeros(n,)
delta = 10**(-8)
omega = 1.25
k = 0
M = 100
Cu = -np.triu(A,1)
Cl = -np.tril(A,-1)
D = np.diag(np.diag(A))
L = D - omega*Cl
U = D - omega*Cu

def Forward(L,n,b):
    z = np.zeros(n)
    for i in xrange(n):
        tmp_sum = np.dot(L[i,:i],z[:i])
        z[i] = (b[i] - tmp_sum)/L[i,i]    
    return z
Z = Forward(L,n,b)

def Backward(U,n,z):
    x = np.zeros(n)
    for i in range(n-1,-1,-1):
        tmp_sum = np.dot(U[i,i+1:n],x[i+1:n])
        x[i] = (z[i] - tmp_sum)/U[i,i]
    return x
X = Backward(U,n,z)

def SOR(z,k):
    z1 = z
    for k in xrange(M):
        r = omega*(np.dot(Cu,z) + b) + (1-omega)*np.dot(D,z)
        z = Forward(L,n,r)
        if np.sqrt(np.inner((z1-z),(z1-z)))<delta:
            return z, k
        else:
            z1 = z.copy()
    return z, k

def SSOR(z):
    z1 = z
    for k in xrange(M):
        r = omega*(np.dot(Cu,z) + b) + (1-omega)*np.dot(D,z)
        z = Forward(L,n,r)
        r1 = omega*(np.dot(Cl,z) + b) + (1-omega)*np.dot(D,z)
        x = Backward(U,n,r1)
        if np.sqrt(np.inner((z1-z),(z1-z)))<delta:
            return z, k
        else:
            z1 = z.copy()    
    return x,k

S = SOR(z,k)
SS = SSOR(z1)

print S
print SS

(array([ 1.,  2., -2.]), 19)
(array([ 1.,  2., -2.]), 19)
