In [4]:
# Problem 1 - Gram-Schmidt and normal equation to solve least-squares problem
import numpy as np
from numpy import dot
from numpy.linalg import inv

A = np.array([[63.,41.,-88.], [42.,60.,51.], [0.,-28.,56.], [126.,82.,-71.]])
b = np.array([[12.],[-17.],[14.],[9.]])

n = len(A)
m = len(np.transpose(A))

def gramschmidt(A,b):
    R = np.zeros((A.shape[1], A.shape[1]))
    Q = np.zeros(A.shape)
    for k in range(0, A.shape[1]):
        R[k, k] = np.sqrt(dot(A[:, k], A[:, k]))
        Q[:, k] = A[:, k]/R[k, k]
        for j in range(k+1, A.shape[1]):
            R[k, j] = dot(Q[:, k], A[:, j])
            A[:, j] = A[:, j] - R[k, j]*Q[:, k]
    prod = dot(np.transpose(Q),Q)
    x = dot(inv(R),dot(inv(prod),dot(np.transpose(Q),b)))
    return Q, R, x


gs = gramschmidt(A,b)
print gs

(array([[ 0.42857143, -0.0952381 , -0.47619048],
       [ 0.28571429,  0.71428571,  0.57142857],
       [ 0.        , -0.66666667,  0.66666667],
       [ 0.85714286, -0.19047619,  0.04761905]]), array([[ 147.,  105.,  -84.],
       [   0.,   42.,   21.],
       [   0.,    0.,  105.]]), array([[ 0.41814059],
       [-0.55238095],
       [-0.05396825]]))


In [32]:
# Problem 2 - Householder Transformation
import numpy as np

test = np.array([[4.,1.,-2.,2.], [1.,2.,0.,1.], [-2.,0.,3.,-2.], [2.,1.,-2.,-1.]])
test2 = np.array([[-2.,-4.,2.], [-2.,1.,2.], [4.,2.,5.]])
n = len(test)
m = len(test2)

def Householder(n,A):
    for k in xrange(n-2):
        q = np.dot(A[k+1:n,k],A[k+1:n,k])
        alpha = -np.sign(A[k+1,k])*np.sqrt(q)
        r = np.sqrt((alpha**2)/2. - (alpha*A[k+1,k])/2.)
        w = np.zeros(n)
        w[k+1] = (A[k+1,k]-alpha)/(2.*r)
        for j in range(k+2,n):
            w[j] = A[j,k]/(2.*r)
        P = np.identity(n) - 2.*np.outer(w,np.transpose(w))
        A = np.dot(P,np.dot(A,P))        
    return A

H1 = Householder(n,test)
H2 = Householder(m,test2)

print H1
print H2

[[  4.00000000e+00  -3.00000000e+00   1.33226763e-16  -9.32587341e-16]
 [ -3.00000000e+00   3.33333333e+00  -1.66666667e+00  -1.11022302e-16]
 [  1.33226763e-16  -1.66666667e+00  -1.32000000e+00   9.06666667e-01]
 [ -9.32587341e-16  -3.33066907e-16   9.06666667e-01   1.98666667e+00]]
[[ -2.00000000e+00   3.57770876e+00  -2.68328157e+00]
 [  4.47213595e+00   2.60000000e+00   2.80000000e+00]
 [  4.44089210e-16   2.80000000e+00   3.40000000e+00]]


In [40]:
# QR algorithm3
import numpy as np

epsilon = 10**(-8)
M = 1000

def QR(n,A,epsilon,M):
    b = np.diag(A,-1)
    l = 1
    while np.linalg.norm(b) >= epsilon:
        Q = np.identity(n)
        for k in xrange(n-1):
            d = np.sqrt(A[k,k]**2 + A[k+1,k]**2)
            c = A[k,k]/d
            s = A[k+1,k]/d
            for j in range(k,n):
                u = c*A[k,j] + s*A[k+1,j]
                if j == k:
                    A[k+1,j] = 0
                else:
                    A[k+1,j] = c*A[k+1,j] - s*A[k,j]
                A[k,j] = u
            G = np.identity(n)
            G[k,k] = c
            G[k+1,k+1] = c
            G[k,k+1] = s
            G[k+1,k] = -s
            Q = dot(Q,np.transpose(G))
        A = dot(A,Q)
        l = l+1
        b = np.diag(A,-1)
        if l>M:
            return np.diag(A)            
    return np.diag(A), l


In [42]:
# Problem 3 & 4 - Use QR to find eigenvalues
C = np.array([[4.,3.,0.], [3.,1.,-1.], [0.,-2.,3.]])
n = len(A)
m = len(B)

AQR = QR(n,H1,epsilon,M)
BQR = QR(m,H2,epsilon,M)
CQR = QR(m,C,epsilon,M)

print AQR
print BQR
print CQR

(array([ 6.84462111,  2.26853141, -2.19751698,  1.08436446]), 645)
(array([ 6., -5.,  3.]), 118)
(array([ 6.04880331,  3.1560105 , -1.2048138 ]), 31)
