In [ ]:
## Lauren Hearn
## MATH5660 ProgHW2
## Due 09.28.17

In [2]:
# Problem 1 - Newton's method
import numpy as np

x0 = 5
delta = 10**(-7) #tolerance
M = 5 #max iterations

def newton(f, fp, x0, delta, M):
    i=1
    while i<=M:
        x1 = x0 - (f(x0)/fp(x0))
        if np.abs(f(x0)) < delta:
            return x1, f(x1)
        else:
            x0 = x1
            i = i+1
            print x0, f(x0)
    return x0,f(x0)

def f(x):
    return x**3 - 5*x**2 + 3*x -7

def fp(x): # derivative of f
    return 3*x**2 - 10*x + 3

p = newton(f,fp,x0,delta,M)
print p

5 8
5 8
5 8
5 8
5 8
(5, 8)


In [3]:
# Problem 2 - Secant method
import numpy as np

x0 = 0
x1 = 1
delta = 10**(-7) #tolerance
M = 100 #max iterations

def secant(f,x0,x1,delta,M):
    i=1
    while i<=M:
        x2 = x1 - f(x1)*((x1-x0)/(f(x1)-f(x0)))
        if np.abs(x2-x1) < delta:
            return x2, f(x2)
        else:
            x0 = x1
            x1 = x2
            i = i+1
    return x1, f(x1)

def f(x):
    return np.exp(x)-np.tan(x)

p = secant(f,x0,x1,delta,M)
print p

## graphically, there are at least 5 roots.
## depending on x0 and x1, we can find them

(-6.2813143694914624, -2.1146279172157278e-15)


In [4]:
# Problem 3 - Steffensen's method
import numpy as np

x0 = 4.5
delta = 10**(-20) #tolerance
M = 10 #max iterations

def steffensen(f, x0, delta, M):
    i=1
    while i<=M:
        x1 = x0 - (f(x0)**2/(f(x0+f(x0))-f(x0)))
        if np.abs(x1-x0) < delta:
            return x1, f(x1)
        else:
            x0 = x1
            i = i+1
            print x0, f(x0)
    return x0,f(x0)

def f(x):
    return np.tan(x) - x

p = steffensen(f,x0,delta,M)
print p

4.49778729038 0.0902537671618
4.49533535232 0.0392415179921
4.49378099934 0.00751485888255
4.49342325937 0.000278679589634
4.49340947694 3.84348168403e-07
4.49340945791 7.36299909931e-13
4.49340945791 8.881784197e-16
(4.4934094579090642, 8.8817841970012523e-16)


In [5]:
# Problem 4 - Newton's method for system of eq.
import numpy as np

x0 = .5
y0 = 1
xm = np.matrix([[x0],[y0]])
delta = 10**(-7) #tolerance
M = 100 #max iterations

def newton(f, Inv, x0, y0, xm, delta, M):
    i=1
    while i<=M:
        xn = xm - Inv(x0,y0)*f(x0,y0)
        x1 = xn.item(0)
        y1 = xn.item(1)
        if np.linalg.norm(xn-xm) < delta:
            return xn, f(x1,y1)
        else:
            x0 = x1
            y0 = y1
            xm = xn
            i = i+1
            print xm, f(x0,y0)
    return xm,f(x0,y0)

def f(x,y): #function matrix
    return np.matrix([[4*y**2+4*y+52*x-19],[169*x**2+3*y**2+111*x-10*y-10]])

def J(x,y): # Jacobian of f
    return np.matrix([[52,(8*y+4)],[(338*x+111),(6*y-10)]])

def Inv(x,y): # inverse of Jacobian of f
    return np.linalg.inv(J(x,y))

#def f1(x,y):
#    return 4*y**2 + 4*y + 52*x - 19

#def f2(x,y):
#    return 169*x**2 + 3*y**2 + 111*x - 10*y - 10

p = newton(f, Inv, x0, y0, xm, delta, M)
print p

[[ 0.21160314]
 [ 0.99971973]] [[  3.14202978e-07]
 [  1.40561949e+01]]
[[ 0.14127495]
 [ 1.30453216]] [[ 0.37164247]
 [ 1.11461509]]
[[ 0.13424788]
 [ 1.30410026]] [[  7.46135012e-07]
 [  8.34572515e-03]]
[[ 0.13419706]
 [ 1.30428332]] [[  1.34042359e-07]
 [  5.37056312e-07]]
(matrix([[ 0.13419705],
        [ 1.30428333]]), matrix([[  0.00000000e+00],
        [  5.32907052e-15]]))
